### ISSUE TITLE
Deploy milestone

### ISSUE THREAD

**Issue by goessebr** [goessebr/testrepo#1]
Gelieve aan te vinken welke voorwaarden van toepassing zijn:

- [ ] Er zijn aanpassingen in production.ini
- [ ] Er zijn aanpassingen aan ES index
- [ ] Er zijn alembic upgrades
- [ ] Er dienen brieven worden toegevoegd op de dgen
- [ ] Deze milestone is afhankelijkheid van deployments andere projecten. Zo ja, welke (Applicatie (versie)):
